# configs/settings/graph_simple.yml
problem_params:
  periods: 10
  ignore_periods: 5
  graph:
    nodes:
      - { id: 0, type: 'warehouse', features: { has_external_supply: 1, is_demand_facing: 0 } }
      - { id: 1, type: 'store',     features: { has_external_supply: 0, is_demand_facing: 1 } }
      - { id: 2, type: 'store',     features: { has_external_supply: 0, is_demand_facing: 1 } }
      - { id: 3, type: 'store',     features: { has_external_supply: 0, is_demand_facing: 1 } }
    edges:
      - [0, 1]  # Warehouse -> Store 1
      - [0, 2]  # Warehouse -> Store 2
      - [0, 3]  # Warehouse -> Store 3

data_params:
  n_samples: 1024
  batch_size: 256 # Note: The current trainer loads the full dataset at once. This is for future compatibility.

optimizer_params:
  learning_rate: 0.00001